select * from costumer


-- Q1. What is the total revenue generated by male vs. female customers?

SELECT Gender,
       SUM(Purchase_Amount) AS revenue
FROM costumer
GROUP BY Gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?


select customer_id , purchase_amount
from costumer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from costumer)

-- Q3. Which are the top 5 products with the highest average review rating?


select item_purchased, ROUND(AVG(review_rating::numeric),2) as "average product rating"
from costumer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,
ROUND(AVG(purchase_amount),2)
from costumer
where shipping_type in ('Standard', 'Express')
group by shipping_type


-- Q5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, 
COUNT (customer_id ) as total_customer,
ROUND(AVG(purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
from costumer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?


select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)/COUNT(*) ,2) as discount_rate
from costumer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as (
select customer_id , previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from costumer
)

select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment

-- Q8.What are the top 3 most purchased products within each category?

with item_count as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count (customer_id ) DESC )as item_rank
from costumer
group by category, item_purchased
)

select item_rank , category , item_purchased, total_orders
from item_counts
where item_rank <=3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?

SELECT age_group, 
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

